name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  frontend:
    name: Frontend checks
    runs-on: ubuntu-latest
    working-directory: frontend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm ci
      - run: npm run lint
      - run: npm run format -- --check
      - run: npm run typecheck
      - run: npm run build

  backend:
    name: Backend checks
    runs-on: ubuntu-latest
    working-directory: backend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm ci
      - run: npm run lint
      - run: npm run format -- --check
      - run: npm run typecheck
      - run: npm run build
